version: "3.9"
services:
  warehouse:
    container_name: WarehouseApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongoDB
      - redisCache
    networks:
      - commonNetwork
  mongoDB:
    container_name: mongoDBWarehouse
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - "27017:27017"
    networks:
      - commonNetwork
  redisCache:
    container_name: redisCacheWarehouse
    image: 'redis:7.0.4'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - commonNetwork
networks:
  commonNetwork:
