version: "3.9"
services:
  warehouse:
    container_name: WarehouseApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
      - redis_server
    networks:
      - common_network
  mongo_db:
    container_name: mongodb_warehouse
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - 27017:27017
    networks:
      - common_network
  redis_server:
    container_name: redis_warehouse
    image: 'redis:7.0.4'
    restart: always
    ports:
      - 6379:6379
    networks:
      - common_network
networks:
  common_network:
