version: "3.9"
services:
  app:
    container_name: SpringBootApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
 #   volumes:
 #     - ./:/app/app
    volumes:
      - ./.docker/redis:/redis-service/logs
    depends_on:
      - mongo_db
      - redis_server
  mongo_db:
    #container_name: mongodb
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
  redis_server:
    container_name: redis
    image: 'redis'
    restart: always
    ports:
      - 6379:6379