version: "3.9"
services:
  app:
    container_name: SpringBootApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app/app
